module.exports.config = {
    name: "fyter",
    version: "1.0.0",
    hasPermssion: 2,
    credits: "𝙈𝙧𝙏𝙤𝙢𝙓𝙭𝙓",
    description: "War In Chatbox",
    commandCategory: "wargroup",
    usages: "[fyter]",
    cooldowns: 7,
    dependencies: {
        "fs-extra": "",
        "axios": ""
    }
}

module.exports.run = async function({ api, args, Users, event}) {
 var mention = Object.keys(event.mentions)[0];
    
 let name =  event.mentions[mention];
    var arraytag = [];
        arraytag.push({id: mention});
    var a = function (a) { api.sendMessage(a, event.threadID); }
a("");
setTimeout(() => {a({body: "BTTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MNMMAAAAAARRRRROOOOOUUUUUUUUU 😂😂😂😂🤔" })}, 1000);
setTimeout(() => {a({body: "BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN 😂😂😂😂CCCCCCHHHHHHOOOOOOOOODDDDDDDD GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUU "})}, 2000);
setTimeout(() => {a({body: "777333RRR111 BAAHN KKK111 LLLLAAALLL GGGGAAANNNDDD VVVIICHHH M3RRR444 LLLLOOORRRAAAA 😂😂😂😂" })}, 3000);
setTimeout(() => {a({body: "ETTTTEEEXXXXXIIIII KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA 😂😂😂😂 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKKKAAAAAAAA BBBBOOOOBSSS CCCCCCCCCCHHHHHHHUUUUUUUUUSSSSSSSUUUUUUUU " })}, 4000);
setTimeout(() => {a({body: "BӇ❍SDIIƘƐ AƲƘAAT Ӈ❍ƝII CͦӇAӇIIYƐ AADII SƐ ⱮA CͦӇƲDAƝƐ AA ᎶYA LAƝD BӇ❍SDIIƘƐ ♡• || _[🙂]~🖤 •|𝙈𝙧𝙏𝙤𝙢𝙓𝙭𝙓 ƝƐ ACͦӇӇ❍ ƘII ⱮAA CͦӇ❍DII ӇAII" })}, 5000);
setTimeout(() => {a({body: "TƐƦII ⱮAA ƘII CͦӇӇ❍❍T BSDƘ ƦAƝDIIƘ BƐƐƐJ TƐƦII ⱮAAA ƘII CͦӇƲT ⱮƐƐƐ AAAᎶ LᎶAA DƲƝᎶAAA ƤƐTƦ❍L DAAAAL Ƙ •||•●┼┼──🦋☘️•|" })}, 6000);
setTimeout(() => {a({body: "BӇ❍SDII Ƙ AƲƘAAAT BƝAAA ⱮƐƦƐ ❍ⱲƝƐƦ SƐ ƑYTT ƘƦƐᎶAAA BSDƘ CͦӇƲTIIYAAA ADⱮII LAƝD ӇAII TƲ ⟴᭄⃢🍂༄* *✥❥⃟😌" })}, 7000);
setTimeout(() => {a({body: "ᎶAAƝD ⱮƦⱲAA LƐ AᎶƦ JADAAA ƘӇƲJLII ӇAII T❍ BSDƘ ⱮADƐƦCͦӇ❍D ƘII AƲLAAAD ♡• || _[🙂]~🖤 •|TƐƦII ⱮAAA ƘII CͦӇƲTTT ӇAƦAⱮII SALƐ •||•●┼┼──🦋☘️•|" })}, 8000);
setTimeout(() => {a({body: "TƐƦII  ᎶAAAƝD ⱮAAƦ LƲƝᎶAA BӇ❍SDIIƘƐ ⱮADDƦƐCͦӇ❍D BӇƐƝ Ƙ L❍DƐ CͦӇƲTIIYA ƘII AƲLAAD ƦAƝDII Ƙ 🎸🎭━━•☆°•°•💗SƲAƦ SALA•||•●┼┼──🦋☘️•|" })}, 9000);
setTimeout(() => {a({body: "TƐƦII ᎶAƝD ⱮƐ AIISA SƲTLII B❍ⱮB Ƒ❍DƲƝᎶA TƐƦII ᎶAƝD ƘALII Ӈ❍ JAYᎶII BӇƐƝCͦӇ❍D SAALƐ ⱮADƦCͦӇ❍D ƘⱮIIƝƐ 🎸🎭━━•☆°•°•💗" })}, 10000);
setTimeout(() => {a({body: "ⱮAAA Ƙ L❍DƐ BӇ❍SDIIƘƐ SALƐ AB ƘAƦ TYƤƤ TƐƦII ⱮAA CͦӇƲDD ᎶYII BӇ❍SDIIƘƐ BӇ❍T LƐᎶƐƝD BƝ ƦAӇA TӇAA CͦӇƲTIIYA SALAA •||•●┼┼──🦋☘️•|" })}, 12000);
setTimeout(() => {a({body: "JAB AƲƘAAT ƝAA Ӈ❍ T❍ ƑYT ƘƦƝƐ ⱮT AAYAA ƘAƦ BӇ❍SDIIƘƐ ƦAƝDII Ƙ ƤIILLƐƐ ⱮDƦCͦӇ❍D •||•●┼┼──🦋☘️•|🎸🎭━━•☆°•°•💗" })}, 14000);
setTimeout(() => {a({body: "TƐƦIIII ᎶAAƝD ⱮƐ ƘƐLAA DAL DƲƝᎶAA Ɱ❍TAAA ⱲALAAA BӇƐƝ Ƙ L❍DƐ CͦӇƲTIIYAA SALAA AƲƘATLƐSSS BӇ❍SDIIƘAAA🎸🎭━━•☆°•°•💗" })}, 16000);
setTimeout(() => {a({body: "TƐƦIII ⱮAA ƘII CͦӇӇ❍❍T BӇ❍SDIIƘƐ 🦋🤍🍒🕊️🥀💗BӇƐƝ Ƙ L❍DƐ BIIƝA TƐLL Ƙ ⱮAƦƲƝᎶAA ⱮDƦCͦӇ❍DD ♡• || _[🙂]~🖤 •|" })}, 18000);
setTimeout(() => {a({body: "BӇ❍SDIIƘƐƐ ƦAƝDIIƘ SALƐ ӇAƦAⱮII 💋⃟̥̥̥̥̥̥̥̥̥̩̩̥̩̊̊̊̊̊̊̊🦋⃟̲̱̥ᴬᴬᴰᴵ😅ƘAƦ AB TYYƤ BSDƘ ⱮADƦCͦӇ❍D CͦӇƲTIIYAA SALAAA •||•●┼┼──🦋☘️•|BӇƐƝ Ƙ L❍DƐ " })}, 20000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIII KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA 😂😂😂😂😂😝😝😝😝😝❤️ MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD ☹️☹️☹️☹️☹️😝😝😝☹️❤️❤️ " })}, 22000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMMMMMAAAAAA TTTTTTTTAAAAAAIIIIIILLLLLLLL LLLLLLGGGGGGGAAAAAA KKKKKKKKKAAAAAAAA LLLLAAAAND DDDDDDOIUUUUUUU 😝😝😝😂😂😂😂❤️ " })}, 25000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD MAROU 😂😂😂😂❤️❤️❤️❤️❤️" })} , 27000);
setTimeout(() => {a({body: "TTTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMMMMMAAAAAA TTTTTTTTAAAAAAIIIIIILLLLLLLL LLLLLLGGGGGGGAAAAAA KKKKKKKKKAAAAAAAA LLLLAAAAND DDDDDDOIUUUUUUU 😝😝😝😂😂😂😂❤️❤️❤️❤️❤️TTTTEEEXXXXXIIIII KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU NNNNAASSAAAALLLL KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOOLLLLLLLLLLLAAAAAAAADDDDDD 😂😂" })} , 30000);
setTimeout(() => {a({body: "<3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD CCCCCCHHHHHHOOOOOOOOODDDDDDDD DDDDDDOIUUUUUUU GGGGGGGGGAAAAAAAA MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 < " })} , 34000);
setTimeout(() => {a({body: "BBBBB33333HHHHHHHAAAAAANNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA PPPPPPUUUUUUUSSSHHHHH KEERRROOOOUUUU 😂😂😂😂❤️❤️❤️❤️🖕🏻🖕🏻🖕🏻🖕🏻 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMAAA UUUUUUNNNNNGGGGGLLLLLIIIIIII DDDDDDOIUUUUUUU 😂" })} , 36000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUU" })} , 38000);
setTimeout(() => {a({body: "3 <3 <3 <3 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN CCCCCCHHHHHHOOOOOOOOODDDDDDDD:p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3" })} , 40000);
setTimeout(() => {a({body: "13 <3 <3 <3 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN CCCCCCHHHHHHOOOOOOOOODDDDDDDD:p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3" })} , 43000);
setTimeout(() => {a({body: "😆😆😆😆😆😆😆😆😆😆😆👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅TTTTTTEEEEEEERRRRRRRRRRRUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋UU😋😋😋😋😋😋😋😋😋😋😋😋MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWKKKKKKKKKKKKKKOOOOOOOOOOOOOOOOOOOOOOOOOOOOO😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋XXXXXXXXXXXXXXXXXXXXXXXXXXXXHHHHHHHOOOOOODDDDDDDDDDDUUUUUUUUUUUUUUUUUUUUUUUUUU🤣🤣🤣" })} , 46000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD CCCCCCHHHHHHOOOOOOOOODDDDDDDD DDDDDDOIUUUUUUU GGGGGGGGGAAAAAAAA MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p" })} , 48000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD MAROU 😂😂" })} , 49900);
setTimeout(() => {a({body: "LLLLLOOOOOOOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣LL🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣BBBBBBBBBBBBHHHHHHHHHHHHHHNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN😋N😋N😋N😋N😋N😋N😋NN😋😋" })} , 50500);
setTimeout(() => {a({body: "TTTTEEEXXXXXIIIII KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU NNNNAASSAAAALLLL KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOOLLLLLLLLLLLAAAAAAAADDDDDD 😂😂" })} , 51000);




  
  }